### ISSUE TITLE
Does not crawl if config provided

### ISSUE THREAD

**Issue by ghostrydr** [oyvindeh/ucss#37]
`ucss -h http://www.host.com -c http://www.host.com/path/to.css` crawls the page and outputs the urls as expected. however there are links to subdomains and youtube so this option is not suitable.

`ucss -g config_ucss.js` doesn't seem to crawl beyond the `pages.crawl` option in the config

content of config_ucss.js

    module.exports = {
        "pages": {
            "crawl": "http://www.host.ca/",

            "exclude": [
                "http://www.youtube.com/",
                "http://sub1.host.ca/*",
                "http://sub2.host.ca/*"
            ]
        },
        
        "css": [
            "http://www.host.ca/css/style-min.css"
        ]
    };

**Comment by oyvindeh** [comment]
Thanks for the bug report, and sorry for the slow response. I will look into this as soon I get the chance, but I can not make any promises about when.

**Comment by oyvindeh** [comment]
I've finally been able to have a look at this; sorry that it took so long!

From what I understand, you expect the crawler to go beyond the domain to crawl. But it should never do this: Links to e.g. YouTube will never be followed. This is because your CSS is not relevant for YouTube.  

Thus, the links you have in pages.exclude are not needed: pages.exclude is only for pages on your crawled domain that is to be skipped by the crawler.

Let me know if I've misunderstood. Also, if you have suggestions for how to make the documentation/example clearer, please let me know.

**Comment by ghostrydr** [comment]
Here's some sample output from using this command `ucss -h http://www.shaw.ca -c http://www.shaw.ca/uploadedfiles/ecomm/css/shaw-min.css`


![image](https://cloud.githubusercontent.com/assets/4332509/8810609/3a5eb976-2fad-11e5-8e59-574265cb025d.png)

![image](https://cloud.githubusercontent.com/assets/4332509/8810625/688b8ebe-2fad-11e5-8663-71f5f3185b2c.png)

As you can see it's crawling subdomains (would like to disable that as they are entirely separate sites) as well as Facebook, YouTube and iTunes.

Using just `ucss` with essentially the same config as above does produce output although it doesn't appear to crawl beyond the specified page. It's flagging styles that I know for sure are used on other pages (315 used, 3352 unused?... nope!)

**Comment by oyvindeh** [comment]
Thanks, I can reproduce this. I will try to look into it when I'm back from vacation next week.

**Comment by oyvindeh** [comment]
Seems like there may be two separate issues:
* Sometimes, pages outside of given domain is visited by crawler.
* The used selectors count seems too low for the specified page. This may indicate that not all pages are visited.

I think I've fixed the first issue (in a separate branch, 82b66787dff7b41cd796ef8852482719a849b967). It was caused by protocol relative URIs (e.g. "//newsroom.shaw.ca/") being handled as domain relative URLs, which is clearly wrong.

As for the second issue: I ran ucss towards your site and got the following (both with config and from command line):

```
3674 (1303 used, 2364 unused, 304 duplicates, 2 ignored)
```
This is a higher number of used selectors than you got. Does it seem correct?

(Btw, it seems like you have a broken link somewhere, pointing to hhttps://www.shaw.ca/store/cart/orderLeadForm2.jsp)

**Comment by ghostrydr** [comment]
There's a good possibility that those results are more accurate. We still have a legacy stylesheet that's still in use (which is the root of this ol' project of mine). I'll take a closer look when I have some time (hopefully next week).

Thanks for pointing out the broken link. I'm surprised our marketing dept. hasn't pointed that out yet... lol

**Comment by oyvindeh** [comment]
Great! I will try to integrate and launch the changes mid next week, when I am back from travel. Until then, please use the branch mentioned above.

**Comment by oyvindeh** [comment]
I've integrated and released this now. Very sorry that it took longer than expected.
